# Site
title:              Diego Luiz
bio:                'Tech and thoughts'
description:        "Blog about my life as a software developer and what I learned."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_GB
url:                http://diegoluiz.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   diegorcl

# Social
# if you don't have any of social below, comment the line.
google:
  plus: https://plus.google.com/u/0/+DiegoLuiz
  analytics: UA-97548691-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            diegorcluiz
facebook:           diegorcl
github:             diegoluiz
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           diegorcluiz
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              diegorcl
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

excerpt_separator: <!--more-->

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
